//Returns a list of all todos whose status is 'TO DO'
//S1 /todos/?status=TO%20DO
//API 1
GET http://localhost:3000/todos/?status=TO%20DO

###
GET http://localhost:3000/todos/?priority=HIGH

###
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS


###
GET http://localhost:3000/todos/?search_q=Play

###
//Returns a specific todo based on the todo ID
//API 2
GET http://localhost:3000/todos/2/

###
//Create a todo in the todo table,
//API 3
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

###

//Updates the details of a specific todo based on the todo ID
//API 4
PUT http://localhost:3000/todos/1/
Content-Type: application/json


{ "status": "DONE" }

###
PUT http://localhost:3000/todos/1/
Content-Type: application/json

{ "priority": "HIGH" }

###
PUT http://localhost:3000/todos/1/
Content-Type: application/json

{ "todo": "Some task" }

###
//Deletes a todo from the todo table based on the todo ID
//API 5
DELETE http://localhost:3000/todos/5/
